#!/usr/bin/env bash
set -e
ghuser=bluesquall
ghrepo=kauhale

hostname=encom
user=flynn
uid=1982
pubkeys="https://en.com/flynn/pubkeys"

usage() {
  echo "please specify the drive to nixify (e.g., /dev/nvme0n1)";
}

while [[ $# -gt 1 ]]; do
  case "$1" in
    -h | --hostname )
      shift
      hostname="$1"
      ;;
    -u | --user )
      shift
      user="$1"
      ;;
    -i | --uid )
      shift
      uid="$1"
      ;;
    -k | --pubkeys )
      shift
      pubkeys="$1"
      ;;
    *)
      usage;
      exit 1;
  esac
  shift
done

pushd /mnt/etc/nixos
rawmain="https://raw.githubusercontent.com/${ghuser}/${ghrepo}/main"
curl -#SLO "${rawmain}/nixos/filesystems.nix"
curl -#SLO "${rawmain}/nixos/configuration.nix"
popd
sed -i "s/encom/${hostname}/" /mnt/etc/nixos/configuration.nix
sed -i "s/flynn/${user}/" /mnt/etc/nixos/configuration.nix
sed -i "s/1982/${uid}/" /mnt/etc/nixos/configuration.nix
mkdir -p /mnt/home/.keys
echo "set password for user $user:"
echo "$(mkpasswd -m sha512crypt)" > /mnt/home/.keys/${user}
chmod 700 /mnt/home/.keys
chmod 600 /mnt/home/.keys/${user}
#sed -i '/^      openssh.authorizedKeys.keys = \[$/r'<(curl -sSL ${pubkeys} | sed 's/^/        "/' | sed 's/$/"/') /mnt/etc/nixos/configuration.nix
time nixos-install --no-root-passwd # doesn't work anyway if mutableUsers=false
