# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a56231a8-746e-4daa-8307-d9d385654b58";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."crypt".device = "/dev/disk/by-uuid/5024b14a-eec1-44c8-9845-dd50b5917f3b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D3B1-2511";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a56231a8-746e-4daa-8307-d9d385654b58";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/a56231a8-746e-4daa-8307-d9d385654b58";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/a56231a8-746e-4daa-8307-d9d385654b58";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/a56231a8-746e-4daa-8307-d9d385654b58";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
